import type { Cafe } from "@/types/cafe";

const suriyansh: Cafe = {
  slug: "suriyansh-burgers",
  name: "Suriyansh Cafe",
  tagline: "Burgers, bites & brews — Clement Town's favourite hangout",
  address: "Clement Town, Near Graphic Era University, Dehradun",
  phone: "+91 89796 16111",
  whatsapp: "918979616111",
  openHours: "10 AM – 11 PM",

  theme: {
    primary: "#F59E0B",
    primaryRgb: "245 158 11",
  },

  todaySpecial: "b2",

  loyalty: {
    stampsRequired: 5,
    reward: "1 Free Cold Coffee ☕",
  },

  features: {
    games: true,
    aiAssistant: true,
    customisations: true,
  },

  aiName: "Cafe Buddy",

  categories: [
    { id: "burgers", label: "Burgers", emoji: "🍔" },
    { id: "cafe-bites", label: "Cafe Bites", emoji: "🥪" },
    { id: "sides", label: "Sides", emoji: "🍟" },
    { id: "hot-drinks", label: "Hot Drinks", emoji: "☕" },
    { id: "cold-drinks", label: "Cold Drinks", emoji: "🥤" },
    { id: "desserts", label: "Desserts", emoji: "🍰" },
  ],

  menu: [
    // ── Burgers ──────────────────────────────────────────────────────────────
    {
      id: "b1",
      name: "Classic Smash Burger",
      description: "Double smash patty, American cheese, secret sauce, pickles",
      price: 199,
      category: "burgers",
      isVeg: false,
      emoji: "🍔",
      badges: ["bestseller"],
      customisations: [
        {
          id: "patty",
          label: "Patty",
          required: false,
          multiple: false,
          options: [
            { id: "single", label: "Single Patty", price: 0 },
            { id: "double", label: "Double Patty", price: 40 },
          ],
        },
        {
          id: "addons",
          label: "Add-ons",
          required: false,
          multiple: true,
          options: [
            { id: "cheese", label: "Extra Cheese", price: 20 },
            { id: "jalapeno", label: "Jalapeños", price: 15 },
            { id: "egg", label: "Fried Egg", price: 25 },
          ],
        },
      ],
    },
    {
      id: "b2",
      name: "Dynamite Zinger",
      description: "Crispy spicy chicken, jalapeños, chipotle mayo, coleslaw",
      price: 219,
      category: "burgers",
      isVeg: false,
      emoji: "🌶️",
      badges: ["spicy", "bestseller"],
      customisations: [
        {
          id: "spice",
          label: "Spice Level",
          required: true,
          multiple: false,
          options: [
            { id: "medium", label: "Medium 🌶️", price: 0 },
            { id: "hot", label: "Hot 🌶️🌶️", price: 0 },
            { id: "extra-hot", label: "Extra Hot 🔥", price: 0 },
          ],
        },
      ],
    },
    {
      id: "b3",
      name: "Double Patty Monster",
      description: "Two smash patties, double cheese, caramelised onions, BBQ",
      price: 269,
      category: "burgers",
      isVeg: false,
      emoji: "🔥",
      badges: ["must-try", "spicy"],
    },
    {
      id: "b4",
      name: "Garden Crunch",
      description: "Crispy potato patty, fresh lettuce, tomato, mint chutney",
      price: 169,
      category: "burgers",
      isVeg: true,
      emoji: "🥬",
      customisations: [
        {
          id: "addons",
          label: "Add-ons",
          required: false,
          multiple: true,
          options: [
            { id: "cheese", label: "Extra Cheese", price: 20 },
            { id: "sauce", label: "Extra Sauce", price: 10 },
          ],
        },
      ],
    },
    {
      id: "b5",
      name: "Mushroom Swiss Melt",
      description: "Sautéed mushrooms, Swiss cheese, truffle aioli",
      price: 189,
      category: "burgers",
      isVeg: true,
      emoji: "🍄",
      badges: ["new"],
    },

    // ── Cafe Bites ────────────────────────────────────────────────────────────
    {
      id: "c1",
      name: "Grilled Chicken Sandwich",
      description: "Tender grilled chicken, lettuce, tomato, honey mustard on toasted bread",
      price: 169,
      category: "cafe-bites",
      isVeg: false,
      emoji: "🥪",
      badges: ["bestseller"],
    },
    {
      id: "c2",
      name: "Veg Club Sandwich",
      description: "Triple-decker with cucumber, tomato, cheese, mint chutney",
      price: 139,
      category: "cafe-bites",
      isVeg: true,
      emoji: "🥙",
    },
    {
      id: "c3",
      name: "Paneer Tikka Wrap",
      description: "Smoky paneer tikka, onions, peppers, green chutney in a rumali wrap",
      price: 159,
      category: "cafe-bites",
      isVeg: true,
      emoji: "🌯",
      badges: ["must-try"],
    },
    {
      id: "c4",
      name: "Chicken Kathi Roll",
      description: "Spiced chicken strips, egg, caramelised onions, schezwan sauce",
      price: 149,
      category: "cafe-bites",
      isVeg: false,
      emoji: "🌮",
      badges: ["spicy"],
    },
    {
      id: "c5",
      name: "Cheese Toast",
      description: "Thick-cut bread, three-cheese blend, herbs, oven-grilled",
      price: 99,
      category: "cafe-bites",
      isVeg: true,
      emoji: "🍞",
    },
    {
      id: "c6",
      name: "Nachos Platter",
      description: "Tortilla chips, salsa, jalapeños, cheese dip, sour cream",
      price: 149,
      category: "cafe-bites",
      isVeg: true,
      emoji: "🧀",
      badges: ["bestseller"],
    },

    // ── Sides ─────────────────────────────────────────────────────────────────
    {
      id: "s1",
      name: "Loaded Fries",
      description: "Crispy fries, cheese sauce, jalapeños, sour cream",
      price: 129,
      category: "sides",
      isVeg: true,
      emoji: "🍟",
      badges: ["bestseller"],
      customisations: [
        {
          id: "size",
          label: "Size",
          required: false,
          multiple: false,
          options: [
            { id: "regular", label: "Regular", price: 0 },
            { id: "large", label: "Large", price: 30 },
          ],
        },
      ],
    },
    {
      id: "s2",
      name: "Onion Rings",
      description: "Beer-battered crispy rings with dipping sauce",
      price: 99,
      category: "sides",
      isVeg: true,
      emoji: "🧅",
    },
    {
      id: "s3",
      name: "Chicken Wings (6 pcs)",
      description: "Tossed in buffalo or BBQ sauce, blue cheese dip",
      price: 179,
      category: "sides",
      isVeg: false,
      emoji: "🍗",
      customisations: [
        {
          id: "sauce",
          label: "Sauce",
          required: true,
          multiple: false,
          options: [
            { id: "buffalo", label: "Buffalo 🔥", price: 0 },
            { id: "bbq", label: "BBQ 🍯", price: 0 },
            { id: "honey-mustard", label: "Honey Mustard", price: 0 },
          ],
        },
      ],
    },
    {
      id: "s4",
      name: "Coleslaw",
      description: "Creamy house-made coleslaw",
      price: 59,
      category: "sides",
      isVeg: true,
      emoji: "🥗",
    },

    // ── Hot Drinks ────────────────────────────────────────────────────────────
    {
      id: "h1",
      name: "Cappuccino",
      description: "Espresso with steamed milk and thick foam",
      price: 99,
      category: "hot-drinks",
      isVeg: true,
      emoji: "☕",
      badges: ["bestseller"],
      customisations: [
        {
          id: "size",
          label: "Size",
          required: false,
          multiple: false,
          options: [
            { id: "regular", label: "Regular", price: 0 },
            { id: "large", label: "Large", price: 30 },
          ],
        },
      ],
    },
    {
      id: "h2",
      name: "Masala Chai",
      description: "House-blend spiced tea with ginger, cardamom, and elaichi",
      price: 49,
      category: "hot-drinks",
      isVeg: true,
      emoji: "🍵",
      badges: ["bestseller"],
    },
    {
      id: "h3",
      name: "Hot Chocolate",
      description: "Rich dark cocoa, steamed milk, whipped cream, choco shavings",
      price: 119,
      category: "hot-drinks",
      isVeg: true,
      emoji: "🍫",
      badges: ["must-try"],
    },
    {
      id: "h4",
      name: "Americano",
      description: "Double espresso with hot water — bold and clean",
      price: 89,
      category: "hot-drinks",
      isVeg: true,
      emoji: "☕",
    },
    {
      id: "h5",
      name: "Lemon Ginger Tea",
      description: "Fresh lemon, ginger, honey — great for cold days",
      price: 59,
      category: "hot-drinks",
      isVeg: true,
      emoji: "🍋",
    },

    // ── Cold Drinks ───────────────────────────────────────────────────────────
    {
      id: "v1",
      name: "Cold Coffee",
      description: "Rich cold brew, milk, whipped cream",
      price: 99,
      category: "cold-drinks",
      isVeg: true,
      emoji: "🧋",
      badges: ["bestseller"],
    },
    {
      id: "v2",
      name: "Oreo Shake",
      description: "Thick Oreo milkshake, extra cookies on top",
      price: 129,
      category: "cold-drinks",
      isVeg: true,
      emoji: "🥤",
      badges: ["must-try"],
    },
    {
      id: "v3",
      name: "Fresh Lemonade",
      description: "Freshly squeezed with mint and soda",
      price: 79,
      category: "cold-drinks",
      isVeg: true,
      emoji: "🍋",
    },
    {
      id: "v4",
      name: "Mango Lassi",
      description: "Alphonso mango with thick creamy yogurt",
      price: 89,
      category: "cold-drinks",
      isVeg: true,
      emoji: "🥭",
    },
    {
      id: "v5",
      name: "Virgin Mojito",
      description: "Fresh mint, lime, sugar syrup, crushed ice, soda",
      price: 89,
      category: "cold-drinks",
      isVeg: true,
      emoji: "🌿",
      badges: ["new"],
    },
    {
      id: "v6",
      name: "Strawberry Smoothie",
      description: "Fresh strawberries blended with yogurt and honey",
      price: 109,
      category: "cold-drinks",
      isVeg: true,
      emoji: "🍓",
    },

    // ── Desserts ──────────────────────────────────────────────────────────────
    {
      id: "d1",
      name: "Nutella Waffle",
      description: "Crispy Belgian waffle, Nutella drizzle, banana slices, powdered sugar",
      price: 149,
      category: "desserts",
      isVeg: true,
      emoji: "🧇",
      badges: ["bestseller"],
    },
    {
      id: "d2",
      name: "Chocolate Brownie",
      description: "Warm fudgy brownie served with a scoop of vanilla ice cream",
      price: 129,
      category: "desserts",
      isVeg: true,
      emoji: "🍫",
      badges: ["must-try"],
    },
    {
      id: "d3",
      name: "Gulab Jamun (2 pcs)",
      description: "Soft melt-in-mouth gulab jamuns in rose-saffron syrup",
      price: 79,
      category: "desserts",
      isVeg: true,
      emoji: "🍮",
    },
    {
      id: "d4",
      name: "Ice Cream Scoop",
      description: "Choose from Vanilla, Chocolate, or Strawberry",
      price: 69,
      category: "desserts",
      isVeg: true,
      emoji: "🍦",
      customisations: [
        {
          id: "flavour",
          label: "Flavour",
          required: true,
          multiple: false,
          options: [
            { id: "vanilla", label: "Vanilla", price: 0 },
            { id: "chocolate", label: "Chocolate", price: 0 },
            { id: "strawberry", label: "Strawberry", price: 0 },
          ],
        },
      ],
    },
  ],
};

export default suriyansh;
